---
title: "Overview"
date: today
editor_options: 
  chunk_output_type: console
---

{{< include _setup.qmd >}}

```{r}
library(tidyverse)
library(gopheR)
```

```{r}
with_gopher_con(function(c) {
  gopher_query(c, "
    SELECT
      (SELECT COUNT(*) FROM sample)   AS samples,
      (SELECT COUNT(*) FROM readset) AS readsets,
      (SELECT COUNT(*) FROM assembly) AS assemblies,
      (SELECT COUNT(*) FROM mag)      AS mags,
      (SELECT COUNT(*) FROM object)   AS objects,
      (SELECT COUNT(*) FROM edge)     AS edges
  ")
}) |>
  pivot_longer(cols = everything(), names_to = "Type", values_to = "Count") |>
  knitr::kable()
```

## Example query: MAGs in high moisture samples

```{r}
with_gopher_con(function(c) {
  gopher_query(c, "
    SELECT DISTINCT
      REPLACE(e1.child_id,  'mag:',    '') AS mag_id,
      REPLACE(e2.parent_id, 'sample:', '') AS sample_id,
      meas.value AS moisture
    FROM edge AS e1
    JOIN edge AS e2
      ON e2.child_id = e1.parent_id
    JOIN measurement AS meas
      ON meas.object_id = e2.parent_id
    WHERE e1.child_id  LIKE 'mag:%'
      AND e1.edge_type = 'observed_in'
      AND e2.edge_type = 'collected_from'
      AND e2.parent_id LIKE 'sample:%'
      AND meas.key = 'moisture'
      AND meas.value > 50
    ORDER BY mag_id, sample_id;
  ")
}) |>
  summarize(
    MAGs = paste(mag_id, collapse = ", "),
    moisture = mean(moisture),
    .by = "sample_id"
  ) |>
  arrange(desc(moisture)) |>
  knitr::kable()
```

## Sample map

```{r}
with_gopher_con(function(c) {
  gopher_query(c, "
    SELECT s.* 
    FROM site as s
  ")
}) |>
  leaflet::leaflet() |>
    leaflet::addProviderTiles(leaflet::providers$CartoDB.Positron) |>
    leaflet::addCircleMarkers(
      lng = ~as.numeric(longitude), 
      lat = ~as.numeric(latitude),
      radius = 6,
      popup = ~site_id)
```


